# .prettierrc.yaml

# General formatting options applicable to Markdown files
tabWidth: 4 # Number of spaces per indentation level
useTabs: false # Indent lines with spaces instead of tabs
proseWrap: "preserve" # Preserve existing line breaks in Markdown

# Future restrictions can be added below as needed
# For example:
# printWidth: 120       # Maximum line length
# semi: true            # Add a semicolon at the end of statements (optional for Markdown)
