import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'category', label: '首页', items: ['README']}],
  AcademicSidebar: [{type: 'autogenerated', dirName: 'academic-resources'}],
  GrowthSidebar: [{type: 'autogenerated', dirName: 'growth-path'}],

  // HelpSidebar: [{type: 'autogenerated', dirName: 'Community-hub'}],
  HelpSidebar: [
    {
      type: 'category',
      label: '共建社区',
      items: [
        'community-hub/about-wiki',
        'community-hub/README',
      ]
    },
  ],
  LifeSidebar: [
    {
      type: 'category',
      label: '生活相关',
      items: [
        'campus-life/first-lesson-of-school',
        'campus-life/different-courses',
        'campus-life/class-attendance',
        'campus-life/major-transfer-guide',
        'campus-life/minor-or-dual-degree',
        'campus-life/student-email',
        'campus-life/library',
        'campus-life/resolving-conflicts',
        'campus-life/social-connections',
        'campus-life/getting-out-of-singleness',
        'campus-life/medical-insurance',
        'campus-life/international-exchange',
        'campus-life/faq-national-student-loan',
        'campus-life/scholarship',
        'campus-life/work-study-program',
      ],
    },
    {
      type: 'category',
      label: '圆梦帮扶',
      items: [
        'campus-life/scholarship',
        'campus-life/work-study-program',
        // 你可以继续补充其它 Dream-Realization-Assistance 相关文档
      ],
    },
  ],

  repositorySidebar: [
    {
      type: 'category',
      label: '计算机技术',
      items: [
        // SurfingTutorial 总览
        'general-skills/computer-basic/SurfingTutorial',
        // 自动生成 SurfingTutorial 下的各章节
        {
          type: 'autogenerated',
          dirName: 'general-skills/computer-basic/SurfingTutorial/chap2',
        },
        {
          type: 'autogenerated',
          dirName: 'general-skills/computer-basic/SurfingTutorial/chap3',
        },
        {
          type: 'autogenerated',
          dirName: 'general-skills/computer-basic/SurfingTutorial/chap4',
        },
      ],
    },
    // 你可以继续补充其它 Computer 相关内容
    {
      type: 'category',
      label: '通用技能',
      items: [
        'general-skills/computer-basic/SurfingTutorial',
        'general-skills/search-platforms',
        'general-skills/student-discounts',
      ],
    },
    {
      type: 'category',
      label: '效率工具',
      items: [
        'general-skills/tools',
      ],
    },
  ],
};

export default sidebars;
